# Generated by Django 2.2.4 on 2019-09-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('strength', models.FloatField(default=0)),
                ('money', models.FloatField(default=0)),
                ('start_place', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_content', models.CharField(max_length=50)),
                ('Q_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=200)),
                ('money', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='store_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='store_style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store_category')),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cost', models.IntegerField(default=3)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store_category')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store_style')),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('store_route', models.CharField(max_length=200)),
                ('hours', models.IntegerField(default=4)),
                ('people_num', models.IntegerField(default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('satisfaction', models.IntegerField(default=3)),
                ('content', models.CharField(max_length=200)),
                ('is_reviewed', models.IntegerField(default=0)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.route')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_about', models.CharField(max_length=20)),
                ('choice_no', models.IntegerField(default=3)),
                ('choice_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store_style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
    ]
