# Generated by Django 2.2.4 on 2019-09-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='store_id',
            new_name='store',
        ),
    ]
